-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.1.0
-- Generated: 2016-09-08 17:04

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_mixpanel_users_1 (
    "schema_vendor"                VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"                VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"               VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                      CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                  TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                     VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                     VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                   VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "$distinct_id"                 VARCHAR(4096) ENCODE LZO,
    "$properties.$city"            VARCHAR(4096) ENCODE LZO,
    "$properties.$country_code"    VARCHAR(4096) ENCODE LZO,
    "$properties.$created"         TIMESTAMP     ENCODE LZO,
    "$properties.$email"           VARCHAR(4096) ENCODE LZO,
    "$properties.$first_name"      VARCHAR(4096) ENCODE LZO,
    "$properties.$last_name"       VARCHAR(4096) ENCODE LZO,
    "$properties.$last_seen"       TIMESTAMP     ENCODE LZO,
    "$properties.$region"          VARCHAR(4096) ENCODE LZO,
    "$properties.last seen"        TIMESTAMP     ENCODE LZO,
    "$properties.referring domain" VARCHAR(4096) ENCODE LZO,
    "$properties.referring url"    VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_mixpanel_users_1 IS 'iglu:com.mixpanel/users/jsonschema/1-0-0';
