addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.7.0")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.1")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt-coursier" % "1.14")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.25")
