-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.1
-- Generated: 2016-07-07 04:24

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_olark_transcript_1 (
    "schema_vendor"                                 VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                                   VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"                                 VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"                                VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                                       CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                                   TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                                      VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                                      VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                                    VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "groups"                                        VARCHAR(5000) ENCODE LZO,
    "id"                                            VARCHAR(4096) ENCODE LZO,
    "items"                                         VARCHAR(5000) ENCODE LZO,
    "kind"                                          VARCHAR(4096) ENCODE LZO,
    "operators.1234.email_address"                  VARCHAR(4096) ENCODE LZO,
    "operators.1234.id"                             VARCHAR(4096) ENCODE LZO,
    "operators.1234.kind"                           VARCHAR(4096) ENCODE LZO,
    "operators.1234.nickname"                       VARCHAR(4096) ENCODE LZO,
    "operators.1234.username"                       VARCHAR(4096) ENCODE LZO,
    "tags"                                          VARCHAR(5000) ENCODE LZO,
    "visitor.browser"                               VARCHAR(4096) ENCODE LZO,
    "visitor.chat_feedback.comments"                VARCHAR(4096) ENCODE LZO,
    "visitor.chat_feedback.friendliness"            SMALLINT      ENCODE LZO,
    "visitor.chat_feedback.knowledge"               SMALLINT      ENCODE LZO,
    "visitor.chat_feedback.overall_chat"            SMALLINT      ENCODE LZO,
    "visitor.chat_feedback.responsiveness"          SMALLINT      ENCODE LZO,
    "visitor.city"                                  VARCHAR(4096) ENCODE LZO,
    "visitor.conversation_begin_page"               VARCHAR(4096) ENCODE LZO,
    "visitor.country"                               VARCHAR(4096) ENCODE LZO,
    "visitor.country_code"                          VARCHAR(4096) ENCODE LZO,
    "visitor.custom_fields.favorite_color"          VARCHAR(4096) ENCODE LZO,
    "visitor.custom_fields.my_internal_customer_id" VARCHAR(4096) ENCODE LZO,
    "visitor.email_address"                         VARCHAR(4096) ENCODE LZO,
    "visitor.full_name"                             VARCHAR(4096) ENCODE LZO,
    "visitor.id"                                    VARCHAR(4096) ENCODE LZO,
    "visitor.ip"                                    VARCHAR(15)   ENCODE LZO,
    "visitor.kind"                                  VARCHAR(4096) ENCODE LZO,
    "visitor.operating_system"                      VARCHAR(4096) ENCODE LZO,
    "visitor.organization"                          VARCHAR(4096) ENCODE LZO,
    "visitor.phone_number"                          VARCHAR(4096) ENCODE LZO,
    "visitor.region"                                VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_olark_transcript_1 IS 'iglu:com.olark/transcript/jsonschema/1-0-0';
