# (probably) nonsense but valid config file for testing
aws:
  # Credentials can be hardcoded or set in environment variables
  access_key_id: SAMPLE KEY
  secret_access_key: SAMPLE SECRET KEY
  s3:
    region: eu-west-1
    buckets:
      assets: spha # DO NOT CHANGE unless you are hosting the jarfiles etc yourself in your own bucket
      jsonpath_assets: # If you have defined your own JSON Schemas, add the s3:// path to your own JSON Path files in your own bucket here
      log: s3://not-a-bucket
      encrypted: false
      enriched:
        good: eg       # e.g. s3://my-out-bucket/enriched/good
        archive: ea    # Where to archive enriched events to, e.g. s3://my-out-bucket/enriched/archive
        stream: es    # Where to archive enriched events to, e.g. s3://my-out-bucket/enriched/archive
      shredded:
        good: sg       # e.g. s3://my-out-bucket/shredded/good
        bad: sb       # e.g. s3://my-out-bucket/shredded/bad
        errors:      # Leave blank unless :continue_on_unexpected_error: set to true below
        archive: sa    # Not required for Postgres currently
    consolidate_shredded_output: false
  emr:
    ami_version: 5.9.0      # Don't change this
    region: eu-west-1        # Always set this
    jobflow_role: EMR_EC2_DefaultRole # Created using $ aws emr create-default-roles
    service_role: EMR_DefaultRole     # Created using $ aws emr create-default-roles
    placement:      # Set this if not running in VPC. Leave blank otherwise
    ec2_subnet_id: E # Set this if running in VPC. Leave blank otherwise
    ec2_key_name: sample
    bootstrap: []           # Set this to specify custom boostrap actions. Leave empty otherwise
    software:
      hbase:                # To launch on cluster, provide version, "0.92.0", keep quotes
      lingual:              # To launch on cluster, provide version, "1.1", keep quotes
    # Adjust your Hadoop cluster below
    jobflow:
      job_name: test file (invalid) # Give your job a name
      master_instance_type: m1.medium
      core_instance_count: 2
      core_instance_type: m1.medium
      core_instance_ebs:    # Optional. Attach an EBS volume to each core instance.
        volume_size: 500    # Gigabytes
        volume_type: "gp2"
        volume_iops: 5000
        ebs_optimized: false # Defaults to true
      task_instance_count: 0 # Increase to use spot instances
      task_instance_type: m1.medium
      task_instance_bid: 0.015 # In USD. Adjust bid, or leave blank for non-spot-priced (i.e. on-demand) task instances
    bootstrap_failure_tries: 3 # Number of times to attempt the job in the event of bootstrap failures
enrich:
  output_compression: NONE # Compression only supported with Redshift, set to NONE if you have Postgres targets. Allowed formats: NONE, GZIP
storage:
  versions:
    rdb_loader: 0.13.0
    rdb_shredder: 0.14.0         # Version of the Spark Shredding process
    hadoop_elasticsearch: 0.1.0 # Version of the Hadoop to Elasticsearch copying process
monitoring:
  tags: {} # Name-value pairs describing this job
  logging:
    level: DEBUG # You can optionally switch to INFO for production
  snowplow:
