-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.1.0
-- Generated: 2015-07-30 16:56

-- Source: iglu:com.amazon.aws.cloudfront/wd_access_log/jsonschema/1-0-4

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_amazon_aws_cloudfront_wd_access_log_1 (
    "schema_vendor"               VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_name"                 VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_format"               VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_version"              VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "root_id"                     CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"                 TIMESTAMP        ENCODE RAW       NOT NULL,
    "ref_root"                    VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                    VARCHAR(1500)    ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                  VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "date_time"                   TIMESTAMP        ENCODE LZO       NOT NULL,
    "c_ip"                        VARCHAR(45)      ENCODE LZO,
    "cs_bytes"                    DOUBLE PRECISION ENCODE RAW,
    "cs_cookie"                   VARCHAR(4096)    ENCODE LZO,
    "cs_host"                     VARCHAR(2000)    ENCODE LZO,
    "cs_method"                   VARCHAR(3)       ENCODE LZO,
    "cs_protocol"                 VARCHAR(5)       ENCODE LZO,
    "cs_referer"                  VARCHAR(8192)    ENCODE LZO,
    "cs_uri_query"                VARCHAR(8192)    ENCODE LZO,
    "cs_uri_stem"                 VARCHAR(8192)    ENCODE LZO,
    "cs_user_agent"               VARCHAR(2000)    ENCODE LZO,
    "sc_bytes"                    DOUBLE PRECISION ENCODE RAW,
    "sc_status"                   VARCHAR(3)       ENCODE LZO,
    "ssl_cipher"                  VARCHAR(64)      ENCODE LZO,
    "ssl_protocol"                VARCHAR(32)      ENCODE LZO,
    "time_taken"                  DOUBLE PRECISION ENCODE RAW,
    "x_edge_location"             VARCHAR(32)      ENCODE LZO,
    "x_edge_request_id"           VARCHAR(2000)    ENCODE LZO,
    "x_edge_response_result_type" VARCHAR(32)      ENCODE LZO,
    "x_edge_result_type"          VARCHAR(32)      ENCODE LZO,
    "x_forwarded_for"             VARCHAR(45)      ENCODE LZO,
    "x_host_header"               VARCHAR(2000)    ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);
