-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.2.0
-- Generated: 2015-11-17 10:49

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_google_analytics_enhanced_ecommerce_action_field_object_1 (
    "schema_vendor"  VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_name"    VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_format"  VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_version" VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "root_id"        CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"    TIMESTAMP        ENCODE LZO       NOT NULL,
    "ref_root"       VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "ref_tree"       VARCHAR(1500)    ENCODE RUNLENGTH NOT NULL,
    "ref_parent"     VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "affiliation"    VARCHAR(500)     ENCODE LZO,
    "coupon"         VARCHAR(500)     ENCODE LZO,
    "currency"       CHAR(3)          ENCODE LZO,
    "id"             VARCHAR(500)     ENCODE LZO,
    "list"           VARCHAR(500)     ENCODE LZO,
    "option"         VARCHAR(500)     ENCODE LZO,
    "revenue"        DOUBLE PRECISION ENCODE RAW,
    "shipping"       DOUBLE PRECISION ENCODE RAW,
    "step"           INT              ENCODE LZO,
    "tax"            DOUBLE PRECISION ENCODE RAW,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_google_analytics_enhanced_ecommerce_action_field_object_1 IS 'iglu:com.google.analytics.enhanced-ecommerce/actionFieldObject/jsonschema/1-0-0';
