/*
 * Copyright (c) 2014 Snowplow Analytics Ltd. All rights reserved.
 *
 * This program is licensed to you under the Apache License Version 2.0,
 * and you may not use this file except in compliance with the Apache License Version 2.0.
 * You may obtain a copy of the Apache License Version 2.0 at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Apache License Version 2.0 is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Apache License Version 2.0 for the specific language governing permissions and limitations there under.
 */
package com.snowplowanalytics.snowplow.enrich
package hadoop
package shredder

// Scalaz
import scalaz._
import Scalaz._

// Snowplow Utils
import com.snowplowanalytics.util.Tap._

// Snowplow Common Enrich
import common._
import outputs.CanonicalOutput

/**
 * A loader for Snowplow enriched events - i.e. the
 * TSV files generated by the Snowplow Enrichment
 * process.
 */
object EnrichedEventLoader {

  private val FieldCount = 104

  private object FieldIndexes { // 0 indexed
    val collectorTstamp = 2
    val eventId = 6
    val contexts = 47
    val ueProperties = 54
  }

  /**
   * Converts the source string into a 
   * ValidatedCanonicalOutput.
   *
   * @param line A line of data to convert
   * @return either a set of validation
   *         Failures or a CanonicalOutput
   *         Success.
   */
  def toEnrichedEvent(line: String): ValidatedCanonicalOutput = {

    val fields = line.split("\t")
    val len = fields.length
    if (len != FieldCount)
      return s"Line does not match Snowplow enriched event (expected $FieldCount fields; found $len)".failNel[CanonicalOutput]

    val event = new CanonicalOutput().tap { e =>
      e.contexts = fields(FieldIndexes.contexts)
      e.ue_properties = fields(FieldIndexes.ueProperties)
    }

    // Get and validate the event ID
    val eventId = validateUuid(fields(FieldIndexes.eventId))
    for (id <- eventId) { event.event_id = id }

    // Get and validate the collector timestamp
    val collectorTstamp = validateTimestamp(fields(FieldIndexes.collectorTstamp))
    for (tstamp <- collectorTstamp) { event.collector_tstamp = tstamp }

    (eventId.toValidationNel |@| collectorTstamp.toValidationNel) {
      (_,_) => event
    }
  }

  // TODO: implement this
  def validateUuid(str: String): ValidatedString = str.success

  // TODO: implement this
  def validateTimestamp(str: String): ValidatedString = str.success
}
