-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.1
-- Generated: 2016-06-11 02:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_statusgator_status_change_1 (
    "schema_vendor"   VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"     VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"   VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"         CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"     TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"        VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"        VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"      VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "current_status"  VARCHAR(4096) ENCODE LZO,
    "favicon_url"     VARCHAR(4096) ENCODE LZO,
    "home_page_url"   VARCHAR(4096) ENCODE LZO,
    "last_status"     VARCHAR(4096) ENCODE LZO,
    "occurred_at"     TIMESTAMP     ENCODE LZO,
    "service_name"    VARCHAR(4096) ENCODE LZO,
    "status_page_url" VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_statusgator_status_change_1 IS 'iglu:com.statusgator/status_change/jsonschema/1-0-0';
