-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.1
-- Generated: 2016-07-02 06:16

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_mailgun_message_delivered_1 (
    "schema_vendor"   VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"     VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"   VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"         CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"     TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"        VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"        VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"      VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "message_id"      VARCHAR(4096) ENCODE LZO,
    "x_mailgun_sid"   VARCHAR(4096) ENCODE LZO,
    "body_plain"      VARCHAR(4096) ENCODE LZO,
    "domain"          VARCHAR(4096) ENCODE LZO,
    "event"           VARCHAR(4096) ENCODE LZO,
    "message_headers" VARCHAR(4096) ENCODE LZO,
    "recipient"       VARCHAR(4096) ENCODE LZO,
    "signature"       VARCHAR(4096) ENCODE LZO,
    "timestamp"       VARCHAR(4096) ENCODE LZO,
    "token"           VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_mailgun_message_delivered_1 IS 'iglu:com.mailgun/message_delivered/jsonschema/1-0-0';
