---
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets:
  - type              : "awss3"
    access_key_id     : <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key : <%= ENV['AWS_SECRET_KEY'] %>

# Required: packages to be deployed
packages:
  # AWS S3 plain upload example
  - name     : "hadoop-shred-hosted-asset"        # Just for convenience
    bucket   : "snowplow-hosted-assets"
    path     : "3-enrich/scala-hadoop-shred"
    region   : "us-west-1"
    publish  : true
    override : true
    continue_on_conflict : false
    version  : <%= FUNC['sbt_version(3-enrich/scala-hadoop-shred/)'] %>

    # Required IF '--check-version' is passed: will assert that both versions are the same
    build_version : <%= ENV['TRAVIS_TAG'] %>

    # Optional: Build commands
    build_commands:
      - sbt assembly

    # Required: Artifact. Version will be inserted between prefix and suffix
    artifacts:
      - type   : "asis"
        prefix : "snowplow-hadoop-shred-"
        suffix : ".jar"
        binary_paths:
          - "3-enrich/scala-hadoop-shred/target/scala-2.10/scala-hadoop-shred"
