-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.0
-- Generated: 2016-02-18 18:48

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_optimizely_visitor_1 (
    "schema_vendor"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"      VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"   VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"          CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"      TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"         VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"         VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "browser"          VARCHAR(4096) ENCODE LZO,
    "browser_version"  VARCHAR(4096) ENCODE LZO,
    "device"           VARCHAR(4096) ENCODE LZO,
    "device_type"      VARCHAR(4096) ENCODE LZO,
    "ip"               VARCHAR(4096) ENCODE LZO,
    "location_city"    VARCHAR(4096) ENCODE LZO,
    "location_country" VARCHAR(4096) ENCODE LZO,
    "location_region"  VARCHAR(4096) ENCODE LZO,
    "mobile"           BOOLEAN       ENCODE RAW,
    "mobile_id"        VARCHAR(4096) ENCODE LZO,
    "os"               VARCHAR(4096) ENCODE LZO,
    "platform_id"      VARCHAR(4096) ENCODE LZO,
    "platform_version" VARCHAR(4096) ENCODE LZO,
    "referrer"         VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_optimizely_visitor_1 IS 'iglu:com.optimizely/visitor/jsonschema/1-0-0';
