-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.2.0
-- Generated: 2016-03-31 15:52

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_amazon_aws_lambda_java_context_1 (
    "schema_vendor"                          VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                            VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"                          VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"                         VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                                CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                            TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                               VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                               VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                             VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "aws_request_id"                         VARCHAR(4096) ENCODE LZO,
    "client_context.client.app_package_name" VARCHAR(4096) ENCODE LZO,
    "client_context.client.app_title"        VARCHAR(4096) ENCODE LZO,
    "client_context.client.app_version_code" VARCHAR(4096) ENCODE LZO,
    "client_context.client.app_version_name" VARCHAR(4096) ENCODE LZO,
    "client_context.custom"                  VARCHAR(4096) ENCODE LZO,
    "client_context.environment"             VARCHAR(4096) ENCODE LZO,
    "function_name"                          VARCHAR(4096) ENCODE LZO,
    "identity.identity_id"                   VARCHAR(4096) ENCODE LZO,
    "identity.identity_pool_id"              VARCHAR(4096) ENCODE LZO,
    "log_group_name"                         VARCHAR(4096) ENCODE LZO,
    "log_stream_name"                        VARCHAR(4096) ENCODE LZO,
    "memory_limit_in_mb"                     BIGINT        ENCODE LZO,
    "remaining_time_millis"                  BIGINT        ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_amazon_aws_lambda_java_context_1 IS 'iglu:com.amazon.aws.lambda/java_context/jsonschema/1-0-0';
