-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.1
-- Generated: 2016-06-17 10:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_amazon_aws_lambda_s3_notification_event_1 (
    "schema_vendor"                         VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                           VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"                         VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"                        VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                               CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                           TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                              VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                              VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                            VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "aws_region"                            VARCHAR(4096) ENCODE LZO,
    "event_name"                            VARCHAR(4096) ENCODE LZO,
    "event_source"                          VARCHAR(4096) ENCODE LZO,
    "event_time"                            TIMESTAMP     ENCODE LZO,
    "event_version"                         VARCHAR(4096) ENCODE LZO,
    "request_parameters.source_ip_address"  VARCHAR(15)   ENCODE LZO,
    "response_elements.x_amz_id_2"          VARCHAR(4096) ENCODE LZO,
    "response_elements.x_amz_request_id"    VARCHAR(4096) ENCODE LZO,
    "s3.bucket.arn"                         VARCHAR(4096) ENCODE LZO,
    "s3.bucket.name"                        VARCHAR(4096) ENCODE LZO,
    "s3.bucket.owner_identity.principal_id" VARCHAR(4096) ENCODE LZO,
    "s3.configuration_id"                   VARCHAR(4096) ENCODE LZO,
    "s3.object.e_tag"                       VARCHAR(4096) ENCODE LZO,
    "s3.object.key"                         VARCHAR(4096) ENCODE LZO,
    "s3.object.size"                        BIGINT        ENCODE LZO,
    "s3.object.version_id"                  VARCHAR(4096) ENCODE LZO,
    "s3.s3_schema_version"                  VARCHAR(4096) ENCODE LZO,
    "user_identity.principal_id"            VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_amazon_aws_lambda_s3_notification_event_1 IS 'iglu:com.amazon.aws.lambda/s3_notification_event/jsonschema/1-0-0';
