:targets:
  - :name:     # Insert your own name to identify the database
    :type:     redshift
    :host:     # Insert Redshfit host
    :database: # Insert database name
    :port:     # Insert database port
    :username: # Insert username with relevant credentials to run the below queries
    :password: # Insert user password
:steps:
  - :name: 01-events
    :queries:
      - :name: 01-events
        :file: /snowplow/5-data-modeling/sql-runner/redshift/sql/mobile-recalculate/01-events.sql
  - :name: 02-sessions
    :queries:
      - :name: 02-sessions
        :file: /snowplow/5-data-modeling/sql-runner/redshift/sql/mobile-recalculate/02-sessions.sql
  - :name: 03-dau
    :queries:
      - :name: 03-dau
        :file: /snowplow/5-data-modeling/sql-runner/redshift/sql/mobile-recalculate/03-dau.sql
