:targets:
  - :name:     # Insert your own name to identify the database
    :type:     redshift
    :host:     # Insert Redshfit host
    :database: # Insert database name
    :port:     # Insert database port
    :username: # Insert username with relevant credentials to run the below queries
    :password: # Insert user password
:steps:
  - :name: 01-identity-stitching
    :queries:
      - :name: 01-01-cookie-id-to-user-id
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/01-identity-stitching/01-01-cookie-id-to-user-id.sql
  - :name: 01-identity-stitching
    :queries:
      - :name: 01-02-join-users
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/01-identity-stitching/01-02-join-users.sql
  - :name: 02-sessions
    :queries:
      - :name: 02-01-basic
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/02-sessions/02-01-basic.sql
  - :name: 02-sessions
    :queries:
      - :name: 02-02-geo
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/02-sessions/02-02-geo.sql
      - :name: 02-03-landing-page
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/02-sessions/02-03-landing-page.sql
      - :name: 02-02-exit-page
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/02-sessions/02-04-exit-page.sql
      - :name: 02-05-source
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/02-sessions/02-05-source.sql
      - :name: 02-06-tech
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/02-sessions/02-06-tech.sql
  - :name: 02-sessions
    :queries:
      - :name: 02-07-move-to-pivot
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/02-sessions/02-07-move-to-pivot.sql
  - :name: 03-visitors
    :queries:
      - :name: 03-01-basic
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/03-visitors/03-01-basic.sql
  - :name: 03-visitors
    :queries:
      - :name: 03-02-landing-page
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/03-visitors/03-02-landing-page.sql
      - :name: 03-03-source
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/03-visitors/03-03-source.sql
  - :name: 03-visitors
    :queries:
      - :name: 03-04-move-to-pivot
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/03-visitors/03-04-move-to-pivot.sql
  - :name: 04-page-views
    :queries:
      - :name: 04-01-page-views
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/04-page-views/04-01-page-views.sql
  - :name: 05-structured-events
    :queries:
      - :name: 05-01-structured-events
        :file: snowplow/5-data-modeling/sql-runner/redshift/sql/web-recalculate/05-structured-events/05-01-structured-events.sql
