-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.2.0
-- Generated: 2015-10-06 14:34

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_amazon_aws_ec2_instance_identity_document_1 (
    "schema_vendor"        VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"          VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"        VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"       VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"              CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"          TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"             VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"             VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"           VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "account_id"           VARCHAR(4096) ENCODE LZO,
    "architecture"         VARCHAR(4096) ENCODE LZO,
    "availability_zone"    VARCHAR(4096) ENCODE LZO,
    "billing_products"     VARCHAR(5000) ENCODE LZO,
    "devpay_product_codes" VARCHAR(5000) ENCODE LZO,
    "image_id"             CHAR(12)      ENCODE LZO,
    "instance_id"          CHAR(10)      ENCODE LZO,
    "instance_type"        VARCHAR(4096) ENCODE LZO,
    "kernel_id"            VARCHAR(12)   ENCODE LZO,
    "pending_time"         TIMESTAMP     ENCODE LZO,
    "private_ip"           VARCHAR(15)   ENCODE LZO,
    "ramdisk_id"           VARCHAR(12)   ENCODE LZO,
    "region"               VARCHAR(4096) ENCODE LZO,
    "version"              VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_amazon_aws_ec2_instance_identity_document_1 IS 'iglu:com.amazon.aws.ec2/instance_identity_document/jsonschema/1-0-0';
