CREATE EXTERNAL TABLE IF NOT EXISTS `events` (
tm string,
txn_id string,
user_ipaddress string,
visit_id int,
page_url string,
page_title string,
page_referrer string,
mkt_source string,
mkt_medium string,
mkt_term string,
mkt_content string,
mkt_name string,
ev_category string,
ev_action string,
ev_label string,
ev_property string,
ev_value string,
br_name string,
br_family string,
br_version string,
br_type string,
br_renderengine string,
br_lang string,
br_features array<string>,
br_cookies boolean,
os_name string,
os_family string,
os_manufacturer string,
dvce_type string,
dvce_ismobile boolean,
dvce_screenwidth int,
dvce_screenheight int
)
PARTITIONED BY (dt STRING, user_id STRING)
LOCATION '${EVENTS_TABLE}' ;
