-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.1.0
-- Generated: 2015-08-13 23:54

-- Source: iglu:io.augur.snowplow/identity_lite/jsonschema/1-0-0

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.io_augur_snowplow_identity_lite_1 (
    "schema_vendor"      VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"        VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"      VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"     VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"            CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"        TIMESTAMP     ENCODE RAW       NOT NULL,
    "ref_root"           VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"           VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"         VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "device.id"          VARCHAR(255)  ENCODE LZO NOT NULL,
    "web_traffic.is_bot" BOOLEAN       ENCODE RAW NOT NULL,
    "web_traffic.is_tor" BOOLEAN       ENCODE RAW NOT NULL,
    "consumer.uuid"      VARCHAR(255)  ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);
